Document: generic-mqtt-client
Title: Debian generic-mqtt-client Manual
Author: <insert document author here>
Abstract: This manual describes what generic-mqtt-client is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/generic-mqtt-client/generic-mqtt-client.sgml.gz

Format: postscript
Files: /usr/share/doc/generic-mqtt-client/generic-mqtt-client.ps.gz

Format: text
Files: /usr/share/doc/generic-mqtt-client/generic-mqtt-client.text.gz

Format: HTML
Index: /usr/share/doc/generic-mqtt-client/html/index.html
Files: /usr/share/doc/generic-mqtt-client/html/*.html
